# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-21 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enlight', '0002_auto_20180221_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
